"""VOC 게시판 — **문제를 앱 안에서 접수하고, 절차로 남긴다.**

사내 설치에는 이슈 트래커가 창구가 되지 못한다. 앱 안에 접수 경로가 없으면 문제는
구두로만 오가고 **기록이 남지 않는다** — 같은 문제를 여럿이 따로 말하고, 고쳐졌는지는
말한 사람만 알고, 안 고쳐진 것은 잊힌다.

표를 둘로 나눈다:

    voc_items    한 건 — 제목·내용·지금 상태·어느 화면에서 냈나
    voc_events   그 건에 일어난 일 — 등록·상태 변경·댓글. **지우지 않는다**

`status` 를 건에 두고도 이벤트를 따로 쌓는 이유: 지금 상태만 있으면 「접수됐나 → 보고
있나 → 됐나」 의 중간이 사라지고, 무엇을 했는지가 마지막 한 줄에만 남는다.

`seq` 는 사람이 「VOC 12번」 이라고 부르는 손잡이다 — UUID 는 입으로 못 부른다.

Revision ID: 0050_voc_board
Revises: 0049_revision_rows
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0050_voc_board"
down_revision: Union[str, Sequence[str], None] = "0049_revision_rows"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voc_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column("page_path", sa.String(length=300), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_voc_items_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["status_by_id"],
            ["users.id"],
            name=op.f("fk_voc_items_status_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_voc_items")),
        sa.UniqueConstraint("seq", name=op.f("uq_voc_items_seq")),
    )
    op.create_index(op.f("ix_voc_items_created_at"), "voc_items", ["created_at"], unique=False)
    op.create_index(op.f("ix_voc_items_status"), "voc_items", ["status"], unique=False)
    op.create_table(
        "voc_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("by_id", sa.UUID(), nullable=True),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["by_id"],
            ["users.id"],
            name=op.f("fk_voc_events_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["voc_items.id"],
            name=op.f("fk_voc_events_item_id_voc_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_voc_events")),
    )
    op.create_index(op.f("ix_voc_events_at"), "voc_events", ["at"], unique=False)
    op.create_index(op.f("ix_voc_events_item_id"), "voc_events", ["item_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voc_events_item_id"), table_name="voc_events")
    op.drop_index(op.f("ix_voc_events_at"), table_name="voc_events")
    op.drop_table("voc_events")
    op.drop_index(op.f("ix_voc_items_status"), table_name="voc_items")
    op.drop_index(op.f("ix_voc_items_created_at"), table_name="voc_items")
    op.drop_table("voc_items")
    # ### end Alembic commands ###
